## NumPy Tutorial

In [823]:
!pip install numpy

In [824]:
import numpy as np
from numpy import ndarray
from numpy import datetime64

In [825]:
numbers: list = [1, 2, 3, 4, 5]

In [826]:
other_numbers: list = [1, 4, 9, 16]

## Convert a python array to a numpy array

In [827]:
np_numbers: ndarray = np.array(numbers)

In [828]:
np_numbers

array([1, 2, 3, 4, 5])

In [829]:
type(numbers), type(np_numbers)

(list, numpy.ndarray)

## Numpy array size

In [830]:
np_numbers.shape

(5,)

## Numpy array with many python arrays 

In [831]:
other_np_array: ndarray = np.array(numbers + other_numbers)

In [832]:
other_np_array

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16])

## Create Numpy array from 1 to 5

In [833]:
np_range: ndarray = np.arange(1, 5, dtype = 'float')

In [834]:
np_range

array([1., 2., 3., 4.])

## Create Numpy array from 1 to 20 by 3

In [835]:
np_range: ndarray = np.arange(1, 20, 3)

In [836]:
np_range

array([ 1,  4,  7, 10, 13, 16, 19])

In [837]:
np_range: ndarray = np.arange(0, 10, 0.2)

In [838]:
np_range

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## Create Numpy array from 1 to 20 by 5

In [839]:
np_matrix: ndarray =  np.linspace(1, 20, 5)

In [840]:
np_matrix

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

## Create a numpy array matrix from a python list

In [841]:
numbers_matrix: list = [[1, 2], [3, 4], [3, 4]]

In [842]:
np_matrix: ndarray = np.array(numbers_matrix)

In [843]:
np_matrix

array([[1, 2],
       [3, 4],
       [3, 4]])

In [844]:
np_matrix.shape

(3, 2)

## Create a numpy array logs from 1 to 50 by 10

In [845]:
np_matrix: ndarray = np.logspace(1, 50, 10)

In [846]:
np_matrix

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

## Create a numpy array with zeros with 1 row and 5 columns

In [847]:
np_matrix: ndarray = np.zeros([1, 5])

In [848]:
np_matrix

array([[0., 0., 0., 0., 0.]])

## Create a numpy array matrix with zeros with [1 row x 2 row x 3 columns]

In [849]:
np_matrix: ndarray = np.zeros([1, 2, 3])

In [850]:
np_matrix

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [851]:
np_matrix: ndarray = np.zeros(shape=(1, 2, 3))

In [852]:
np_matrix

array([[[0., 0., 0.],
        [0., 0., 0.]]])

## Create a numpy array matrix with ones with 1 row and 5 columns

In [853]:
np_matrix: ndarray = np.ones([2, 5])

In [854]:
np_matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [855]:
np_ones: ndarray = np.ones(shape=(2, 5))

In [856]:
np_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Create a numpy array for a specific number

In [857]:
np_matrix: ndarray = np.ones([2, 5])

In [858]:
np_matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [859]:
np_matrix = np_matrix * 6

In [860]:
np_matrix

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

## Create a numpy array repeating [1,2] array 3 times

In [861]:
np_matrix: ndarray = np.tile([1, 2], 3)

In [862]:
np_matrix

array([1, 2, 1, 2, 1, 2])

## Create a numpy array repeating elements [1, 2] array 3 times

In [863]:
np_matrix: ndarray = np.repeat([1, 2], 3)

In [864]:
np_matrix

array([1, 1, 1, 2, 2, 2])

## Create a numpy array with random elements with 3 rows and 3 columns

In [865]:
np_matrix: ndarray = np.random.rand(3, 3)

In [866]:
np_matrix

array([[0.61995572, 0.8289809 , 0.15679139],
       [0.0185762 , 0.07002214, 0.48634511],
       [0.60632946, 0.56885144, 0.31736241]])

## Create a numpy array with random from 0 to 100 with 3 rows and 3 columns

In [867]:
np_matrix: ndarray = np.random.randint(0, 100, [3, 3])

In [868]:
np_matrix

array([[74, 66, 88],
       [98, 30, 17],
       [68, 64, 60]])

## Create a numpy array with random numbers between 20 and 60 with 5 numbers

In [869]:
np_matrix: ndarray = np.random.randint(20, 60, 5)

In [870]:
np_matrix

array([34, 37, 59, 55, 37])

## Create a numpy array with negative and positive values with 5 rows and 4 columns

In [871]:
np_matrix: ndarray = np.random.randn(5, 4)

In [872]:
np_matrix

array([[-0.73252618,  0.67381345, -0.43490928, -1.02350373],
       [ 0.12756686,  0.71794121,  0.38893621,  1.07144178],
       [ 1.17822245, -0.9067845 ,  1.71577556,  0.16473423],
       [ 0.50307319, -0.89985433,  1.63186328, -0.5225589 ],
       [-0.57182319,  1.43158861, -0.84254871, -0.51984645]])

## Create a numpy array with unique elements from other numpy array

In [873]:
np_range: ndarray = np.arange(1, 10, 1)

In [874]:
np_range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [875]:
np_matrix: ndarray = np.unique(np_range)

In [876]:
np_matrix

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Create a numpy array matrix with unique elements from other numpy array with number of elements

In [877]:
np_range: ndarray = np.arange(1, 10, 1)

In [878]:
np_range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [879]:
np_matrix: ndarray = np.unique(np_range, return_counts= True)

In [880]:
np_matrix

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 1, 1, 1, 1, 1, 1, 1, 1]))

## Create a numpy array matrix from type float a python list

In [881]:
np_matrix_float: ndarray = np.array(numbers_matrix, dtype = 'float')

In [882]:
np_matrix_float

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

# Create a numpy array with 1 on diagonal

In [883]:
np_matrix_diagonal: ndarray = np.eye(6)

In [884]:
np_matrix_diagonal

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [885]:
np_matrix_diagonal = np_matrix_diagonal * 6

In [886]:
np_matrix_diagonal

array([[6., 0., 0., 0., 0., 0.],
       [0., 6., 0., 0., 0., 0.],
       [0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 6., 0., 0.],
       [0., 0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 0., 6.]])

## Convert a numpy array matrix from type float to a type int

In [887]:
np_matrix_int: ndarray = np_matrix_float.astype('int')

In [888]:
np_matrix_int

array([[1, 2],
       [3, 4],
       [3, 4]])

## Convert a numpy array matrix from type float to a type string

In [889]:
np_matrix_str: ndarray = np_matrix_float.astype('str')

In [890]:
np_matrix_str

array([['1.0', '2.0'],
       ['3.0', '4.0'],
       ['3.0', '4.0']], dtype='<U32')

In [891]:
np_matrix_str[0][0] += str(1)

In [892]:
np_matrix_str

array([['1.01', '2.0'],
       ['3.0', '4.0'],
       ['3.0', '4.0']], dtype='<U32')

## Not a number in numpy

In [893]:
np.nan

nan

## Infinite number in numpy

In [894]:
np.inf

inf

## Using infinite and not a number in numpy

In [895]:
np_matrix_float

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [896]:
np_matrix_float[0][0] = np.nan
np_matrix_float[1][1] = np.inf

In [897]:
np_matrix_float

array([[nan,  2.],
       [ 3., inf],
       [ 3.,  4.]])

## Check if any element is Not a Number 

In [898]:
np.isnan(np_matrix_float)

array([[ True, False],
       [False, False],
       [False, False]])

## Check if any element is Infinite

In [899]:
np.isinf(np_matrix_float)

array([[False, False],
       [False,  True],
       [False, False]])

## Check if any element is Infinite or Not a number

In [900]:
flag = np.isnan(np_matrix_float) | np.isinf(np_matrix_float)

In [901]:
flag

array([[ True, False],
       [False,  True],
       [False, False]])

## Return all infinite and not a number elements

In [902]:
np_matrix_float[flag]

array([nan, inf])

## Erase all infinite and not a number elements

In [903]:
np_matrix_float[flag] = 0

In [904]:
np_matrix_float

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

## Statistical Operations (mean, var, std, med)

In [905]:
numbers_matrix: list = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]

In [906]:
np_matrix: ndarray = np.array(numbers_matrix)

In [907]:
np_matrix

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Mean

In [908]:
np_matrix.mean()

5.5

In [909]:
np.median(np_matrix)

5.5

## Min

In [910]:
np_matrix.min()

1

## Max

In [911]:
np_matrix.max()

10

## Var

In [912]:
np_matrix.var()

8.25

## Std

In [913]:
np_matrix.std()

2.8722813232690143

## Transform shape matrix (shape, reshape, ravel)

In [914]:
numbers_matrix: list = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]

In [915]:
np_matrix: ndarray = np.array(numbers_matrix)

In [916]:
np_matrix

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [917]:
np_matrix.shape

(5, 2)

## Transform matrix with 2 rows and 5 columns

In [918]:
np_matrix.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Transform matrix with 1 rows and 10 columns

In [919]:
np_matrix.reshape(1, 10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [920]:
np_matrix.reshape(1, 10).ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [921]:
np_matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Filter Where condition on numpy array

In [922]:
np_range: ndarray = np.arange(1, 20, 1)

In [923]:
np_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

## Filter elements if greater than 10

In [924]:
np_index_greater_than_10 = np.where(np_range>10)

In [925]:
np_greater_than_10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [926]:
type(np_greater_than_10)

numpy.ndarray

In [927]:
np_greater_than_10: ndarray = np_range[np_index_greater_than_10]

In [928]:
np_greater_than_10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [929]:
np_range>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [930]:
np_greater_than_10: ndarray = np_range[np_range>10]

In [931]:
np_greater_than_10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

## Filter elements if less than 10

In [932]:
np_index_less_than_10 = np.where(np_range<10)

In [933]:
np_index_less_than_10

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),)

In [934]:
type(np_index_less_than_10)

tuple

In [935]:
np_less_than_10: ndarray = np_range[np_index_less_than_10]

In [936]:
np_less_than_10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Filter elements if equal 10

In [937]:
np_equal_10: ndarray = np_range[np.where(np_range==10)]

In [938]:
np_equal_10

array([10])

## Save numpy array to CSV File

In [939]:
np_range: ndarray = np.arange(1, 20, 1)

In [940]:
np_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [941]:
np.savetxt('np_range.csv', np_range, delimiter=',')

## Load numpy array from CSV File

In [942]:
np_range: ndarray = np.loadtxt('np_range.csv', delimiter=',')

In [943]:
np_range

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.])

## Save numpy array to file

In [944]:
np_numbers_0_to_10: ndarray = np.arange(1, 10, dtype = 'float')

In [945]:
np_numbers_0_to_10

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [946]:
np_numbers_10_to_20: ndarray = np.arange(10, 20, dtype = 'float')

In [947]:
np_numbers_10_to_20

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [948]:
np.save('data.npy', np_numbers_0_to_10)

In [949]:
np.savez('both.npz', np_numbers_0_to_10, np_numbers_10_to_20)

## Load numpy array from file

In [950]:
both = np.load('both.npz')

In [951]:
both.files

['arr_0', 'arr_1']

In [952]:
both

In [953]:
np_numbers_0_to_10: ndarray = both[both.files[0]]

In [954]:
np_numbers_0_to_10

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [955]:
np_numbers_10_to_20: ndarray = both[both.files[1]]

In [956]:
np_numbers_10_to_20

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

## Concatenate

In [957]:
np_numbers_0_to_10

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [958]:
np_numbers_10_to_20

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [959]:
np_numbers: ndarray = np.concatenate([np_numbers_0_to_10, np_numbers_10_to_20], axis = 0)

In [960]:
np_numbers

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.])

## Sort and shuffle numpy array

In [961]:
np_numbers_0_to_10: ndarray = np.arange(1, 10, dtype = 'float')

In [962]:
np_numbers_0_to_10

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Shuffle numpy array

In [963]:
np.random.shuffle(np_numbers_0_to_10)

In [964]:
np_numbers_0_to_10

array([2., 8., 3., 1., 9., 5., 4., 7., 6.])

## Sort numpy array

In [965]:
np_numbers_0_to_10.sort()

In [966]:
np_numbers_0_to_10

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Dates on numpy

In [967]:
today: datetime64 = np.datetime64('2020-07-25 00:00:01')

In [968]:
today

numpy.datetime64('2020-07-25T00:00:01')

## Add days

In [969]:
oneday = np.timedelta64(1, 'D')

In [970]:
tomorrow: datetime64 = today + oneday

In [971]:
tomorrow

numpy.datetime64('2020-07-26T00:00:01')

## Add minutes

In [972]:
one_minute = np.timedelta64(1, 'm')

In [973]:
next_minute = today + one_minute

In [974]:
next_minute

numpy.datetime64('2020-07-25T00:01:01')

## Numpy Sin and Cos

In [975]:
x: ndarray = np.arange(0, 10, 0.2)

In [976]:
x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## Sin

In [977]:
np_sin: ndarray = np.sin(x)


In [978]:
np_sin

array([ 0.        ,  0.19866933,  0.38941834,  0.56464247,  0.71735609,
        0.84147098,  0.93203909,  0.98544973,  0.9995736 ,  0.97384763,
        0.90929743,  0.8084964 ,  0.67546318,  0.51550137,  0.33498815,
        0.14112001, -0.05837414, -0.2555411 , -0.44252044, -0.61185789,
       -0.7568025 , -0.87157577, -0.95160207, -0.993691  , -0.99616461,
       -0.95892427, -0.88345466, -0.77276449, -0.63126664, -0.46460218,
       -0.2794155 , -0.0830894 ,  0.1165492 ,  0.31154136,  0.49411335,
        0.6569866 ,  0.79366786,  0.8987081 ,  0.96791967,  0.99854335,
        0.98935825,  0.94073056,  0.85459891,  0.7343971 ,  0.58491719,
        0.41211849,  0.22288991,  0.02477543, -0.17432678, -0.36647913])

## Cos

In [979]:
np_cos: ndarray = np.cos(x)


In [980]:
np_cos

array([ 1.        ,  0.98006658,  0.92106099,  0.82533561,  0.69670671,
        0.54030231,  0.36235775,  0.16996714, -0.02919952, -0.22720209,
       -0.41614684, -0.58850112, -0.73739372, -0.85688875, -0.94222234,
       -0.9899925 , -0.99829478, -0.96679819, -0.89675842, -0.79096771,
       -0.65364362, -0.49026082, -0.30733287, -0.11215253,  0.08749898,
        0.28366219,  0.46851667,  0.63469288,  0.77556588,  0.88551952,
        0.96017029,  0.9965421 ,  0.99318492,  0.95023259,  0.86939749,
        0.75390225,  0.60835131,  0.43854733,  0.25125984,  0.05395542,
       -0.14550003, -0.33915486, -0.51928865, -0.67872005, -0.81109301,
       -0.91113026, -0.97484362, -0.99969304, -0.98468786, -0.93042627])